# simple v1
on: [push]
env:
  RUSTFLAGS: "-D warnings"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check
      - run: cargo check
      - run: cargo clippy --no-deps
      - run: cargo doc
      - run: cargo test

      # same thing with --features=testing
      - run: cargo check --features=testing
      - run: cargo clippy --no-deps --features=testing
      - run: cargo doc --features=testing
      - run: cargo test --no-default-features --features=testing

      # same thing with --features=testing,app_window
      - run: cargo check --features=testing,app_window
      - run: cargo clippy --no-deps --features=testing,app_window
      - run: cargo test --features=testing,app_window
      - run: cargo doc --features=testing,app_window

      # same thing with --features=testing,backend_wgpu
      - run: cargo check --features=testing,backend_wgpu
      - run: cargo clippy --no-deps --features=testing,backend_wgpu
      - run: cargo doc --features=testing,backend_wgpu
      - run: cargo test --features=testing,backend_wgpu