# feature matrix v1
on: [push]
env:
  RUSTFLAGS: "-D warnings"

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        features:
          - ""                              # no features
          - "testing"                       # testing only
          - "testing,app_window"           # testing + app_window
          - "testing,backend_wgpu"         # testing + backend_wgpu

    steps:
      - uses: actions/checkout@v4

      - name: Cache target
        uses: actions/cache@v4
        with:
          key: "${{ runner.os }}-target-${{ matrix.features }}"
          path: "~/.target"

      - name: "Install deps"
        run: sudo apt-get install libwayland-dev
        # require linux and github (non-gitea) env
        if: runner.os == 'Linux' && !env.GITEA_ACTIONS == 'true'

      - name: "CI"
        # expose the raw comma-separated list in FEATURE_FLAGS
        env:
          FEATURE_FLAGS: ${{ matrix.features }}
        run: |
          # if FEATURE_FLAGS is non-empty, prepend "--features="
          if [ -n "$FEATURE_FLAGS" ]; then
            FLAGS="--features=$FEATURE_FLAGS"
          else
            FLAGS=""
          fi

          cargo fmt --check
          cargo check    $FLAGS
          cargo clippy --no-deps $FLAGS
          cargo doc      $FLAGS
          cargo test     $FLAGS